<html>
    <head>
        <meta charset="utf-8" />
        <title>设置地理位置</title>
    </head>
    <body>
        <form action="/index/geo" method="post">
            <p>
                ID: <input type="text" name="id" id="id" />
            </p>
            <p>
                标题: <input type="text" name="title" id="title" />
            </p>
            <p>
                lat: <input type="text" name="lat" id="lat" />
            </p>
            <p>
                long: <input type="text" name="long" id="long" />
            </p>
            <p>
                <input type="submit"  />
            </p>
            
            
        </form>
    </body>
</html>